name: Bora buildar
jobs:
  buidando:
    runs-on: ubuntu-latest
    steps:
      - run: |
          cd ..
          echo $(pwd)
          echo $(ls)
      - name: Criando tag
        run: git tag atual && git push --tags -f
