name: Bora buildar

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: 'Vai buildar o que?'
        required: true
        default: 'Trapezio'
      name2:
        type: choice
        description: 'Vai buildar onde?'
        required: true
        options:
          - 'Academia'
          - 'Casa'
          - 'Praça'
      name3:
        type: boolean
        description: 'Vai buildar quando?'
        required: true
        default: true
jobs:
  buidando:
    runs-on: ubuntu-latest
    steps:
      - name: Buildando
        run: echo "Buildando ${{ github.event.inputs.name }} em ${{ github.event.inputs.name2 }}"