name: Bora buildar

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: 'Vai buildar o que?'
        required: true
        default: 'Trapezio'
      name2:
        type: choice
        description: 'Vai buildar onde?'
        required: true
        options:
          - 'Academia'
          - 'Casa'
          - 'Praça'
      name3:
        type: boolean
        description: 'Vai buildar agora?'
        required: true
        default: true
      name4:
        type: string
        description: 'Bota tag nessa build ai'
        required: false
        default: 'atual'
jobs:
  buidando:
    runs-on: ubuntu-latest
    if: github.event.inputs.name3 == 'true'
    steps:
      - name: Imprimindo inputs
        run: echo "Buildando ${{ github.event.inputs.name }} em ${{ github.event.inputs.name2 }} com tag ${{ github.event.inputs.name4 }}"
      - name: Faz cd ..
        run: cd ..
      - name: Faz pwd
        run: echo $(pwd)
      - name: Criando tag
        run: git tag ${{ github.event.inputs.name4 }} && git push --tags -f
