name: Bora buildar

on:
  workflow_dispatch:
    env:
      date: ${{date +'%Y-%m-%d'}}
    inputs:
      name:
        type: string
        description: 'Vai buildar o que?'
        required: true
        default: 'Trapezio'
      name2:
        type: choice
        description: 'Vai buildar onde?'
        required: true
        options:
          - 'Academia'
          - 'Casa'
          - 'Praça'
      name3:
        type: boolean
        description: 'Vai buildar agora?'
        required: true
        default: true
      name4:
        type: string
        description: 'Bota tag nessa build ai'
        required: false
        default: { env.date }
jobs:
  buidando:
    runs-on: ubuntu-latest
    if: github.event.inputs.name3 == 'true'
    steps:
      - name: Buildando
        run: echo "Buildando ${{ github.event.inputs.name }} em ${{ github.event.inputs.name2 }}"
      - name: Buildando com input
        run: echo "Buildando com tag ${{ github.event.inputs.name4 }} na run ${{github.run_number}}"
